version: '3'
services:
  mongo:
    image: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=gusteau
    volumes:
      - ./mongo:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
  gusteau:
    build: .
    environment:
      - GUSTEAU_DB_HOST=mongo
      - GUSTEAU_DB_PORT=27017
      - GUSTEAU_DB_NAME=gusteau
      - GUSTEAU_SERVICE_PORT=3000
      - GUSTEAU_LOG_LEVEL=info
      - GUSTEAU_JWT_SECRET=53cr37
      - GUSTEAU_JWT_ISSUER=gusteau
    ports:
      - "81:3000"
    links:
      - "mongo:mongo"
